# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='surname',
            field=models.CharField(max_length=24),
        ),
    ]
