# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0003_auto_20170511_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='InContacts',
            new_name='InContact',
        ),
    ]
