# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_of_contacts', '0004_auto_20170511_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='incontact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InContact',
        ),
    ]
