# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0005_auto_20170511_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
