# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_of_contacts', '0007_auto_20170511_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('country', models.CharField(default=None, max_length=24)),
                ('town', models.CharField(default=None, max_length=24)),
                ('phone_nmb', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('birthday', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
