# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0009_auto_20170516_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
    ]
