# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0010_auto_20170516_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='town',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
