# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_of_contacts', '0011_auto_20170516_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='session_key',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
