# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:41
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True),
        ),
    ]
