# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170612_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_nmb',
            field=models.CharField(max_length=12),
        ),
    ]
